### ISSUE TITLE
Updating of the html documentation

### ISSUE THREAD

**Issue by jaabell** [OpenSees/OpenSeesDocumentation#33]
Hi @fmckenna. What is the procedure to update the html visible from the github pages? I've pushed .rst files, but have avoided making changes into the docs as requested in the readme. 

Is there a hook that didn't get activated? Or do you personally do it manually?

**Comment by fmckenna** [comment]
it is a manual process. for other put an issue like this if i don't rerun and push the latest code after the rst files have been accepted.
