### ISSUE TITLE
Parameters of ExpressNewton command 

### ISSUE THREAD

**Issue by tcwjqking** [OpenSees/OpenSeesDocumentation#86]
Hello,
I see an ExpressNewton command on OpenSeesPy's Change log, but there is no corresponding invocation description in the documentation.
How can this command be parameterized, or is there an example of how to invoke it?

**Comment by siwalan** [comment]
@mhscott @zhuminjie

**Comment by zxh804159854** [comment]
You can refer to here，This is the author's article.

https://mp.weixin.qq.com/s/SS5gPc8FwV1XCVsp3xGurA

**Comment by tcwjqking** [comment]
> You can refer to here，This is the author's article.
> 
> https://mp.weixin.qq.com/s/SS5gPc8FwV1XCVsp3xGurA
> 
> and
> 
> https://mp.weixin.qq.com/s/EZlCzOT0QGlMufB7wBlDCg

Thank you. 
But the article only mentions the way to invoke it in tcl format. What I really need more is the order of parameters needed to invoke this command in OpenSeesPy, and what type of values they should enter....

**Comment by mhscott** [comment]
The Python command is the same format as Tcl.

I'm curious why you would like to use ExpressNewton? The algorithm is explicit, i.e., does not use a convergence test, and it's possible the algorithm will not converge to equilibrium and you will never know the difference.

**Comment by tcwjqking** [comment]
> The Python command is the same format as Tcl.
> 
> I'm curious why you would like to use ExpressNewton? The algorithm is explicit, i.e., does not use a convergence test, and it's possible the algorithm will not converge to equilibrium and you will never know the difference.
Since I was testing a very large model, I would have liked to use OpenSeesSP for the simulation, but I found that the compiled SP executable did not have the Triangular Elements: ShellNLDKGT , so I had to try to find a faster algorithm...
